function Find-Control($Name) {
  return $window.FindName($Name)
}

$MainScrollViewer = Find-Control "MainScrollViewer"
$PageEyebrowValue = Find-Control "PageEyebrowValue"
$PageTitleValue = Find-Control "PageTitleValue"
$NavDashboardButton = Find-Control "NavDashboardButton"
$NavScopeButton = Find-Control "NavScopeButton"
$NavTriggerButton = Find-Control "NavTriggerButton"
$NavDeviceButton = Find-Control "NavDeviceButton"
$NavLogsButton = Find-Control "NavLogsButton"
$DashboardPage = Find-Control "DashboardPage"
$SettingsPage = Find-Control "SettingsPage"
$SessionControlPanel = Find-Control "SessionControlPanel"
$TriggerStrategyPanel = Find-Control "TriggerStrategyPanel"
$CoyoteOutputPanel = Find-Control "CoyoteOutputPanel"
$DeviceSafetyPanel = Find-Control "DeviceSafetyPanel"
$LowerPages = Find-Control "LowerPages"
$ScopeRulesPanel = Find-Control "ScopeRulesPanel"
$LogsPanel = Find-Control "LogsPanel"

$StatusValue = Find-Control "StatusValue"
$SessionValue = Find-Control "SessionValue"
$LeftValue = Find-Control "LeftValue"
$DistractionValue = Find-Control "DistractionValue"
$IdleValue = Find-Control "IdleValue"
$DeviceValue = Find-Control "DeviceValue"
$DeviceBadge = Find-Control "DeviceBadge"
$ActualStrengthValue = Find-Control "ActualStrengthValue"
$ActualStrengthSource = Find-Control "ActualStrengthSource"
$LockBadge = Find-Control "LockBadge"
$LockBadgeBorder = Find-Control "LockBadgeBorder"
$DeviceModeCombo = Find-Control "DeviceModeCombo"
$HttpConnectionPage = Find-Control "HttpConnectionPage"
$BleConnectionPage = Find-Control "BleConnectionPage"
$SocketConnectionPage = Find-Control "SocketConnectionPage"
$HttpEndpointInput = Find-Control "HttpEndpointInput"
$HttpLimitAInput = Find-Control "HttpLimitAInput"
$HttpLimitBInput = Find-Control "HttpLimitBInput"
$BleAddressInput = Find-Control "BleAddressInput"
$SocketServerModeCombo = Find-Control "SocketServerModeCombo"
$LocalSocketSettings = Find-Control "LocalSocketSettings"
$RemoteSocketSettings = Find-Control "RemoteSocketSettings"
$LocalSocketHostInput = Find-Control "LocalSocketHostInput"
$LocalSocketPortInput = Find-Control "LocalSocketPortInput"
$SocketServerInput = Find-Control "SocketServerInput"
$SocketBindStatusText = Find-Control "SocketBindStatusText"
$SocketAppLimitsText = Find-Control "SocketAppLimitsText"
$SocketManualAddressText = Find-Control "SocketManualAddressText"
$SocketQrContentText = Find-Control "SocketQrContentText"
$SocketQrImage = Find-Control "SocketQrImage"
$SocketQrPlaceholder = Find-Control "SocketQrPlaceholder"
$CurrentWindowInput = Find-Control "CurrentWindowInput"
$CurrentWindowMatchValue = Find-Control "CurrentWindowMatchValue"
$WindowPickerCombo = Find-Control "WindowPickerCombo"
$RefreshWindowListButton = Find-Control "RefreshWindowListButton"
$WhitelistList = Find-Control "WhitelistList"
$BlacklistList = Find-Control "BlacklistList"
$AddWhitelistButton = Find-Control "AddWhitelistButton"
$RemoveWhitelistButton = Find-Control "RemoveWhitelistButton"
$AddBlacklistButton = Find-Control "AddBlacklistButton"
$RemoveBlacklistButton = Find-Control "RemoveBlacklistButton"
$FocusMinutesInput = Find-Control "FocusMinutesInput"
$LeaveInput = Find-Control "LeaveInput"
$IdleInput = Find-Control "IdleInput"
$OutputModeCombo = Find-Control "OutputModeCombo"
$OverlapModeCombo = Find-Control "OverlapModeCombo"
$ChannelModeCombo = Find-Control "ChannelModeCombo"
$StrengthARangeInput = Find-Control "StrengthARangeInput"
$StrengthBRangeInput = Find-Control "StrengthBRangeInput"
$SocketOutputModeText = Find-Control "SocketOutputModeText"
$CurrentWaveformText = Find-Control "CurrentWaveformText"
$WaveformCombo = Find-Control "WaveformCombo"
$WavePeriodInput = Find-Control "WavePeriodInput"
$WaveIntensityInput = Find-Control "WaveIntensityInput"
$DurationInput = Find-Control "DurationInput"
$MaxContinuousInput = Find-Control "MaxContinuousInput"
$HoldCooldownInput = Find-Control "HoldCooldownInput"
$SoftLimitAInput = Find-Control "SoftLimitAInput"
$SoftLimitBInput = Find-Control "SoftLimitBInput"
$FrequencyBalanceAInput = Find-Control "FrequencyBalanceAInput"
$FrequencyBalanceBInput = Find-Control "FrequencyBalanceBInput"
$StrengthBalanceAInput = Find-Control "StrengthBalanceAInput"
$StrengthBalanceBInput = Find-Control "StrengthBalanceBInput"
$LogList = Find-Control "LogList"

$StartButton = Find-Control "StartButton"
$PauseButton = Find-Control "PauseButton"
$EndButton = Find-Control "EndButton"
$UnlockButton = Find-Control "UnlockButton"
$EmergencyButton = Find-Control "EmergencyButton"
$ManualTestButton = Find-Control "ManualTestButton"
$FloatingMonitorButton = Find-Control "FloatingMonitorButton"
$ConnectButton = Find-Control "ConnectButton"
$ApplySafetyButton = Find-Control "ApplySafetyButton"
$DisconnectButton = Find-Control "DisconnectButton"
$StopButton = Find-Control "StopButton"
$ClearLogsButton = Find-Control "ClearLogsButton"
$ImportConfigButton = Find-Control "ImportConfigButton"
$ExportConfigButton = Find-Control "ExportConfigButton"
$ResetSafeConfigButton = Find-Control "ResetSafeConfigButton"

$script:State = @{
  Running = $false
  Paused = $false
  Locked = $false
  Connected = $false
  DeviceMode = "http"
  WindowState = "writing"
  LastWindowKey = ""
  AwayEpisodeActive = $false
  EpisodeTriggerSent = $false
  SessionSeconds = 45 * 60
  LeftSeconds = 0
  DistractionSeconds = 0
  IdleSeconds = 0
  IdleTriggerSent = $false
  FocusStartedAt = [DateTime]::MinValue
  OutputActive = $false
  OutputHoldUntilWhitelist = $false
  OutputProfile = $null
  OutputEnd = [DateTime]::MinValue
  ActualStrengthKnown = $false
  ActualStrengthA = 0
  ActualStrengthB = 0
  ActualStrengthSource = "未连接"
  HoldRetriggerPending = $false
  HoldCooldownEnd = [DateTime]::MinValue
  HttpRenewAt = [DateTime]::MinValue
  SocketClient = $null
  SocketTransport = $null
  SocketClientId = ""
  SocketTargetId = ""
  SocketServerUri = ""
  SocketReceiveTask = $null
  SocketReceiveBuffer = $null
  LocalSocketServer = $null
  LocalSocketLastError = ""
  SocketWatchdogStopCount = 0
  SocketAppStrengthA = 0
  SocketAppStrengthB = 0
  SocketAppLimitA = 0
  SocketAppLimitB = 0
  SocketHasAppLimits = $false
  SocketStrengthUpdateCount = 0
  SocketServerMode = "local"
}

$script:FloatingMonitorWindow = $null
$script:FloatingStrengthAValue = $null
$script:FloatingStrengthBValue = $null
$script:FloatingDurationValue = $null
$script:FloatingRemainingValue = $null
$script:FloatingSourceValue = $null

